name: Test examples

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: fab21
          channels: conda-forge
          python-version: 3.8

      - name: install
        run: |
          conda env update -f https://dfab.link/mcneel-2021.yml
      - name: Verify imports
        run: |
          python -c "import compas; print(compas.__version__)"
          python -c "import compas_fab; print(compas_fab.__version__)"
          python -c "import compas_rrc; print(compas_rrc.__version__)"
          python -m compas
      - name: Test code samples
        run: |
          for file in ./examples/*.py
          do
          if [[ ${file} =~ ^./examples/[0-1]+ ]]; then
              echo Testing file=${file}
              cat .github/workflows/setup-test.py ${file} | python
          fi
          done
